spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jwtpost
    username: postgres
    password: '@Maxton19'
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework: DEBUG
    org.apache: DEBUG
